SRCFILES:= \
	test-ringbufindex.c \
	../../../arch/platform/cooja/./platform.c \
	../../../arch/platform/cooja/lib/simEnvChange.c \
	../../../arch/platform/cooja/sys/cooja_mt.c \
	../../../arch/platform/cooja/sys/cooja_mtarch.c \
	../../../arch/platform/cooja/./rtimer-arch.c \
	../../../os/dev/slip.c \
	../../../arch/platform/cooja/dev/watchdog.c \
	../../../arch/platform/cooja/dev/beep.c \
	../../../arch/platform/cooja/dev/button-sensor.c \
	../../../arch/platform/cooja/dev/ip.c \
	../../../arch/platform/cooja/dev/leds-arch.c \
	../../../arch/platform/cooja/dev/moteid.c \
	../../../arch/platform/cooja/dev/pir-sensor.c \
	../../../arch/platform/cooja/dev/rs232.c \
	../../../arch/platform/cooja/dev/vib-sensor.c \
	../../../arch/platform/cooja/sys/clock.c \
	../../../arch/platform/cooja/sys/cooja-log.c \
	../../../arch/platform/cooja/cfs/cfs-cooja.c \
	../../../arch/platform/cooja/dev/cooja-radio.c \
	../../../arch/platform/cooja/dev/eeprom.c \
	../../../arch/platform/cooja/./slip-arch.c \
    ../../../arch/platform/cooja/int-master.c \
	../../../os/lib/random.c \
	../../../os/lib/sensors.c \
	../../../os/dev/leds.c \
	../../../os/services/unit-test/example-test.c \
	../../../os/services/unit-test/unit-test.c \
	../../../os/contiki-main.c \
	../../../os/sys/autostart.c \
	../../../os/sys/stimer.c \
	../../../os/sys/log.c \
	../../../os/sys/energest.c \
	../../../os/sys/etimer.c \
	../../../os/sys/node-id.c \
	../../../os/sys/mutex.c \
	../../../os/sys/ctimer.c \
	../../../os/sys/compower.c \
	../../../os/sys/process.c \
	../../../os/sys/rtimer.c \
	../../../os/sys/timer.c \
	../../../os/dev/serial-line.c \
	../../../os/dev/nullradio.c \
	../../../os/lib/dbl-circ-list.c \
	../../../os/lib/crc16.c \
	../../../os/lib/ifft.c \
	../../../os/lib/ccm-star.c \
	../../../os/lib/dbl-list.c \
	../../../os/lib/ringbufindex.c \
	../../../os/lib/list.c \
	../../../os/lib/circular-list.c \
	../../../os/lib/aes-128.c \
	../../../os/lib/trickle-timer.c \
	../../../os/lib/memb.c \
	../../../os/lib/heapmem.c \
	../../../os/lib/assert.c \
	../../../os/lib/ringbuf.c \
	../../../os/net/queuebuf.c \
	../../../os/net/nbr-table.c \
	../../../os/net/packetbuf.c \
	../../../os/net/netstack.c \
	../../../os/net/linkaddr.c \
	../../../os/net/net-debug.c \
	../../../os/net/link-stats.c \
	../../../os/net/mac/mac-sequence.c \
	../../../os/net/mac/mac.c \
	../../../os/net/mac/framer/frame802154e-ie.c \
	../../../os/net/mac/framer/framer-802154.c \
	../../../os/net/mac/framer/nullframer.c \
	../../../os/net/mac/framer/frame802154.c \
	../../../os/net/mac/csma/csma-security.c \
	../../../os/net/mac/csma/anti-replay.c \
	../../../os/net/mac/csma/csma.c \
	../../../os/net/mac/csma/csma-output.c \
	../../../os/net/mac/csma/ccm-star-packetbuf.c \
	../../../os/net/ipv6/uipbuf.c \
	../../../os/net/ipv6/uip-icmp6.c \
	../../../os/net/ipv6/uip-sr.c \
	../../../os/net/ipv6/uip-ds6.c \
	../../../os/net/ipv6/uip-packetqueue.c \
	../../../os/net/ipv6/ip64-addr.c \
	../../../os/net/ipv6/uip-udp-packet.c \
	../../../os/net/ipv6/uip-ds6-route.c \
	../../../os/net/ipv6/psock.c \
	../../../os/net/ipv6/uip-ds6-nbr.c \
	../../../os/net/ipv6/tcpip.c \
	../../../os/net/ipv6/uip6.c \
	../../../os/net/ipv6/resolv.c \
	../../../os/net/ipv6/uip-nameserver.c \
	../../../os/net/ipv6/uip-nd6.c \
	../../../os/net/ipv6/udp-socket.c \
	../../../os/net/ipv6/simple-udp.c \
	../../../os/net/ipv6/sicslowpan.c \
	../../../os/net/ipv6/uiplib.c \
	../../../os/net/routing/rpl-lite/rpl-nbr-policy.c \
	../../../os/net/routing/rpl-lite/rpl-of0.c \
	../../../os/net/routing/rpl-lite/rpl-neighbor.c \
	../../../os/net/routing/rpl-lite/rpl-dag.c \
	../../../os/net/routing/rpl-lite/rpl-timers.c \
	../../../os/net/routing/rpl-lite/rpl-ext-header.c \
	../../../os/net/routing/rpl-lite/rpl.c \
	../../../os/net/routing/rpl-lite/rpl-mrhof.c \
	../../../os/net/routing/rpl-lite/rpl-icmp6.c \
	../../../os/net/routing/rpl-lite/rpl-dag-root.c
