SRCFILES:= \
	   ../../os/net/ipv6/uipbuf.c \
	   ../../os/net/ipv6/uip-icmp6.c \
	   ../../os/net/ipv6/uip-sr.c \
	   ../../os/net/ipv6/uip-ds6.c \
	   ../../os/net/ipv6/uip-packetqueue.c \
	   ../../os/net/ipv6/tcp-socket.c \
	   ../../os/net/ipv6/ip64-addr.c \
	   ../../os/net/ipv6/uip-udp-packet.c \
	   ../../os/net/ipv6/uip-ds6-route.c \
	   ../../os/net/ipv6/psock.c \
	   ../../os/net/ipv6/uip-ds6-nbr.c \
	   ../../os/net/ipv6/tcpip.c \
	   ../../os/net/ipv6/uip6.c \
	   ../../os/net/ipv6/resolv.c \
	   ../../os/net/ipv6/uip-nameserver.c \
	   ../../os/net/ipv6/uip-nd6.c \
	   ../../os/net/ipv6/udp-socket.c \
	   ../../os/net/ipv6/simple-udp.c \
	   ../../os/net/ipv6/sicslowpan.c \
	   ../../os/net/ipv6/uiplib.c \
	   ../../os/net/routing/rpl-lite/rpl-nbr-policy.c \
	   ../../os/net/routing/rpl-lite/rpl-of0.c \
	   ../../os/net/routing/rpl-lite/rpl-neighbor.c \
	   ../../os/net/routing/rpl-lite/rpl-dag.c \
	   ../../os/net/routing/rpl-lite/rpl-timers.c \
	   ../../os/net/routing/rpl-lite/rpl-ext-header.c \
	   ../../os/net/routing/rpl-lite/rpl.c \
	   ../../os/net/routing/rpl-lite/rpl-mrhof.c \
	   ../../os/net/routing/rpl-lite/rpl-icmp6.c \
	   ../../os/net/routing/rpl-lite/rpl-dag-root.c \
	   hello-world.c
